//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderWatcher.FileCallee {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/Test_khoi", ConfigurationName="FileCallee.Test_khoi_Port")]
    public interface Test_khoi_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (CreateFiles_Result) of message CreateFiles_Result does not match the default value (CreateFiles)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Test_khoi:CreateFiles", ReplyAction="*")]
        FolderWatcher.FileCallee.CreateFiles_Result CreateFiles(FolderWatcher.FileCallee.CreateFiles request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/Test_khoi:CreateFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<FolderWatcher.FileCallee.CreateFiles_Result> CreateFilesAsync(FolderWatcher.FileCallee.CreateFiles request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateFiles", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Test_khoi", IsWrapped=true)]
    public partial class CreateFiles {
        
        public CreateFiles() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateFiles_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/Test_khoi", IsWrapped=true)]
    public partial class CreateFiles_Result {
        
        public CreateFiles_Result() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Test_khoi_PortChannel : FolderWatcher.FileCallee.Test_khoi_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Test_khoi_PortClient : System.ServiceModel.ClientBase<FolderWatcher.FileCallee.Test_khoi_Port>, FolderWatcher.FileCallee.Test_khoi_Port {
        
        public Test_khoi_PortClient() {
        }
        
        public Test_khoi_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Test_khoi_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test_khoi_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Test_khoi_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FolderWatcher.FileCallee.CreateFiles_Result FolderWatcher.FileCallee.Test_khoi_Port.CreateFiles(FolderWatcher.FileCallee.CreateFiles request) {
            return base.Channel.CreateFiles(request);
        }
        
        public void CreateFiles() {
            FolderWatcher.FileCallee.CreateFiles inValue = new FolderWatcher.FileCallee.CreateFiles();
            FolderWatcher.FileCallee.CreateFiles_Result retVal = ((FolderWatcher.FileCallee.Test_khoi_Port)(this)).CreateFiles(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FolderWatcher.FileCallee.CreateFiles_Result> FolderWatcher.FileCallee.Test_khoi_Port.CreateFilesAsync(FolderWatcher.FileCallee.CreateFiles request) {
            return base.Channel.CreateFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<FolderWatcher.FileCallee.CreateFiles_Result> CreateFilesAsync() {
            FolderWatcher.FileCallee.CreateFiles inValue = new FolderWatcher.FileCallee.CreateFiles();
            return ((FolderWatcher.FileCallee.Test_khoi_Port)(this)).CreateFilesAsync(inValue);
        }
    }
}
